#!/bin/bash

# - NEMO_SCRIPT_SELECTED_FILE_PATHS: newline-delimited paths for selected files (only if local)
# - NEMO_SCRIPT_SELECTED_URIS: newline-delimited URIs for selected files
# - NEMO_SCRIPT_CURRENT_URI: URI for current location
# - NEMO_SCRIPT_WINDOW_GEOMETRY: position and size of current window
# - NEMO_SCRIPT_NEXT_PANE_SELECTED_FILE_PATHS: newline-delimited paths for selected files in the inactive pane of a split-view window (only if local)
# - NEMO_SCRIPT_NEXT_PANE_SELECTED_URIS: newline-delimited URIs for selected files in the inactive pane of a split-view window
# - NEMO_SCRIPT_NEXT_PANE_CURRENT_URI: URI for current location in the inactive pane of a split-view window

b64file=$(mktemp)
file=$(mktemp)

xclip -selection clipboard -o > $b64file
cat $b64file | base64 --decode > $file
cd ${NEMO_SCRIPT_CURRENT_URI:7}
tar -xzf $file --transform='s/.*\///'
